[manifest]
version = "0.0.1"
priority = 0

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''self.PROFILES = {
    {},
    {},
    {},
}'''
position = "at"
payload = '''self.PROFILES = {
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
}'''
match_indent = true